# Generated by Django 6.0.3 on 2026-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('title', models.CharField(default='Turnament', max_length=25)),
                ('location_plz', models.IntegerField(default=0)),
                ('location_city', models.CharField(default='---', max_length=200)),
                ('link', models.URLField()),
                ('maps', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('color', models.CharField(choices=[('red', 'Rot'), ('blue', 'Blau'), ('green', 'Grün'), ('orange', 'Orange')], default='orange', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_text', models.CharField(max_length=200)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
    ]
