# Generated by Django 6.0.3 on 2026-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorcana_turnament_calender', '0002_event_delete_calenderentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='location_plz',
            field=models.IntegerField(default=0),
        ),
    ]
