# Generated by Django 6.0.3 on 2026-06-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorcana_turnament_calender', '0002_alter_question_answer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('qualification_date', models.DateTimeField()),
            ],
        ),
    ]
