# Generated by Django 6.1 on 2026-08-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorcana_turnament_calender', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='qualification_date',
            field=models.DateField(),
        ),
    ]
