# Generated by Django 6.0.3 on 2026-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorcana_turnament_calender', '0003_event_location_city_event_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_city',
            field=models.CharField(default='---', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_name',
            field=models.CharField(default='---', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Turnament', max_length=200),
        ),
    ]
