# Generated by Django 6.0.3 on 2026-05-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorcana_turnament_calender', '0004_alter_event_location_city_alter_event_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Turnament', max_length=35),
        ),
    ]
