# Generated by Django 6.0.3 on 2026-05-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorcana_turnament_calender', '0005_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(),
        ),
    ]
