# Generated by Django 6.0.3 on 2026-05-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorcana_turnament_calender', '0006_alter_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Turnament', max_length=25),
        ),
    ]
