# Generated by Django 6.0.3 on 2026-05-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorcana_turnament_calender', '0007_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('red', 'Rot'), ('blue', 'Blau'), ('green', 'Grün'), ('orange', 'Orange')], default='orange', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_name',
            field=models.CharField(default='---', max_length=35),
        ),
    ]
